package local_Db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import local_Db.LugarDB;
import local_Db.EquipoDB;
import local_Db.OrdenDB;
import local_Db.HistorialDetallesDB;
import local_Db.FotoDB;

import local_Db.LugarDBDao;
import local_Db.EquipoDBDao;
import local_Db.OrdenDBDao;
import local_Db.HistorialDetallesDBDao;
import local_Db.FotoDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lugarDBDaoConfig;
    private final DaoConfig equipoDBDaoConfig;
    private final DaoConfig ordenDBDaoConfig;
    private final DaoConfig historialDetallesDBDaoConfig;
    private final DaoConfig fotoDBDaoConfig;

    private final LugarDBDao lugarDBDao;
    private final EquipoDBDao equipoDBDao;
    private final OrdenDBDao ordenDBDao;
    private final HistorialDetallesDBDao historialDetallesDBDao;
    private final FotoDBDao fotoDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lugarDBDaoConfig = daoConfigMap.get(LugarDBDao.class).clone();
        lugarDBDaoConfig.initIdentityScope(type);

        equipoDBDaoConfig = daoConfigMap.get(EquipoDBDao.class).clone();
        equipoDBDaoConfig.initIdentityScope(type);

        ordenDBDaoConfig = daoConfigMap.get(OrdenDBDao.class).clone();
        ordenDBDaoConfig.initIdentityScope(type);

        historialDetallesDBDaoConfig = daoConfigMap.get(HistorialDetallesDBDao.class).clone();
        historialDetallesDBDaoConfig.initIdentityScope(type);

        fotoDBDaoConfig = daoConfigMap.get(FotoDBDao.class).clone();
        fotoDBDaoConfig.initIdentityScope(type);

        lugarDBDao = new LugarDBDao(lugarDBDaoConfig, this);
        equipoDBDao = new EquipoDBDao(equipoDBDaoConfig, this);
        ordenDBDao = new OrdenDBDao(ordenDBDaoConfig, this);
        historialDetallesDBDao = new HistorialDetallesDBDao(historialDetallesDBDaoConfig, this);
        fotoDBDao = new FotoDBDao(fotoDBDaoConfig, this);

        registerDao(LugarDB.class, lugarDBDao);
        registerDao(EquipoDB.class, equipoDBDao);
        registerDao(OrdenDB.class, ordenDBDao);
        registerDao(HistorialDetallesDB.class, historialDetallesDBDao);
        registerDao(FotoDB.class, fotoDBDao);
    }
    
    public void clear() {
        lugarDBDaoConfig.getIdentityScope().clear();
        equipoDBDaoConfig.getIdentityScope().clear();
        ordenDBDaoConfig.getIdentityScope().clear();
        historialDetallesDBDaoConfig.getIdentityScope().clear();
        fotoDBDaoConfig.getIdentityScope().clear();
    }

    public LugarDBDao getLugarDBDao() {
        return lugarDBDao;
    }

    public EquipoDBDao getEquipoDBDao() {
        return equipoDBDao;
    }

    public OrdenDBDao getOrdenDBDao() {
        return ordenDBDao;
    }

    public HistorialDetallesDBDao getHistorialDetallesDBDao() {
        return historialDetallesDBDao;
    }

    public FotoDBDao getFotoDBDao() {
        return fotoDBDao;
    }

}
