package local_Db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import local_Db.EquipoDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EQUIPO_DB.
*/
public class EquipoDBDao extends AbstractDao<EquipoDB, Long> {

    public static final String TABLENAME = "EQUIPO_DB";

    /**
     * Properties of entity EquipoDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdEquipo = new Property(1, Integer.class, "idEquipo", false, "ID_EQUIPO");
        public final static Property NumeroEquipo = new Property(2, String.class, "numeroEquipo", false, "NUMERO_EQUIPO");
        public final static Property ListaNombreEquipoIdListaNombre = new Property(3, Integer.class, "listaNombreEquipoIdListaNombre", false, "LISTA_NOMBRE_EQUIPO_ID_LISTA_NOMBRE");
        public final static Property CodigoBarras = new Property(4, String.class, "codigoBarras", false, "CODIGO_BARRAS");
        public final static Property LugarID = new Property(5, long.class, "lugarID", false, "LUGAR_ID");
    };

    private DaoSession daoSession;


    public EquipoDBDao(DaoConfig config) {
        super(config);
    }
    
    public EquipoDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EQUIPO_DB' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ID_EQUIPO' INTEGER," + // 1: idEquipo
                "'NUMERO_EQUIPO' TEXT," + // 2: numeroEquipo
                "'LISTA_NOMBRE_EQUIPO_ID_LISTA_NOMBRE' INTEGER," + // 3: listaNombreEquipoIdListaNombre
                "'CODIGO_BARRAS' TEXT," + // 4: codigoBarras
                "'LUGAR_ID' INTEGER NOT NULL );"); // 5: lugarID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EQUIPO_DB'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EquipoDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer idEquipo = entity.getIdEquipo();
        if (idEquipo != null) {
            stmt.bindLong(2, idEquipo);
        }
 
        String numeroEquipo = entity.getNumeroEquipo();
        if (numeroEquipo != null) {
            stmt.bindString(3, numeroEquipo);
        }
 
        Integer listaNombreEquipoIdListaNombre = entity.getListaNombreEquipoIdListaNombre();
        if (listaNombreEquipoIdListaNombre != null) {
            stmt.bindLong(4, listaNombreEquipoIdListaNombre);
        }
 
        String codigoBarras = entity.getCodigoBarras();
        if (codigoBarras != null) {
            stmt.bindString(5, codigoBarras);
        }
        stmt.bindLong(6, entity.getLugarID());
    }

    @Override
    protected void attachEntity(EquipoDB entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public EquipoDB readEntity(Cursor cursor, int offset) {
        EquipoDB entity = new EquipoDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // idEquipo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // numeroEquipo
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // listaNombreEquipoIdListaNombre
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // codigoBarras
            cursor.getLong(offset + 5) // lugarID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EquipoDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdEquipo(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setNumeroEquipo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setListaNombreEquipoIdListaNombre(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setCodigoBarras(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLugarID(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(EquipoDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(EquipoDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLugarDBDao().getAllColumns());
            builder.append(" FROM EQUIPO_DB T");
            builder.append(" LEFT JOIN LUGAR_DB T0 ON T.'LUGAR_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected EquipoDB loadCurrentDeep(Cursor cursor, boolean lock) {
        EquipoDB entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LugarDB lugarDB = loadCurrentOther(daoSession.getLugarDBDao(), cursor, offset);
         if(lugarDB != null) {
            entity.setLugarDB(lugarDB);
        }

        return entity;    
    }

    public EquipoDB loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<EquipoDB> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<EquipoDB> list = new ArrayList<EquipoDB>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<EquipoDB> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<EquipoDB> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
