package local_Db;

import java.io.Serializable;
import java.util.List;
import local_Db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LUGAR_DB.
 */
public class LugarDB implements Serializable {

    private Long id;
    private String nombre;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LugarDBDao myDao;

    private List<OrdenDB> ordenDBList;

    public LugarDB() {
    }

    public LugarDB(Long id) {
        this.id = id;
    }

    public LugarDB(Long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLugarDBDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<OrdenDB> getOrdenDBList() {
        if (ordenDBList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            OrdenDBDao targetDao = daoSession.getOrdenDBDao();
            List<OrdenDB> ordenDBListNew = targetDao._queryLugarDB_OrdenDBList(id);
            synchronized (this) {
                if(ordenDBList == null) {
                    ordenDBList = ordenDBListNew;
                }
            }
        }
        return ordenDBList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetOrdenDBList() {
        ordenDBList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
